# Generated by Django 2.1.7 on 2019-03-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0003_auto_20190312_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='Tutores',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='permiso',
            name='Alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeRecursos.Alumno'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='Curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeRecursos.Curso'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='Docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeRecursos.Docente'),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
