# Generated by Django 2.1.7 on 2019-03-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=100)),
                ('Nombres', models.CharField(max_length=100)),
                ('Documento', models.CharField(max_length=11)),
                ('FechaDeNacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Sala', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=100)),
                ('Nombres', models.CharField(max_length=100)),
                ('Documento', models.CharField(max_length=11)),
                ('Usuario', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=100)),
                ('Nombres', models.CharField(max_length=100)),
                ('Documento', models.CharField(max_length=11)),
                ('Parentesco', models.CharField(choices=[('Pa', 'Padre'), ('Ma', 'Madre'), ('Ti', 'Tío/a'), ('Ab', 'Abuelo/a'), ('He', 'Hermano/a'), ('Ot', 'Otro')], default='Pa', max_length=1)),
                ('Usuario', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='Tutores',
            field=models.ManyToManyField(to='GestionDeRecursos.Tutor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
